# Generated by Django 4.2.6 on 2023-10-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_animal', models.CharField(choices=[('Y', 'SIM'), ('N', 'NÃO')], db_column='cb_has_animal', default='N', max_length=1)),
                ('type_animal', models.CharField(blank=True, db_column='ch_type_animal', max_length=44, null=True)),
                ('quantity_animal', models.IntegerField(blank=True, db_column='nb_quantity_animal', null=True)),
                ('energy_per_month', models.DecimalField(blank=True, db_column='dc_energy_per_month', decimal_places=2, max_digits=5, null=True)),
                ('car_quantity', models.IntegerField(blank=True, db_column='nb_car_quantity', null=True)),
                ('car_distance_in_km', models.IntegerField(blank=True, db_column='nb_car_distance_in_km', null=True)),
                ('composted_material_quantity', models.DecimalField(blank=True, db_column='dc_composted_material_quantity', decimal_places=2, max_digits=6, null=True)),
                ('has_cultivo', models.CharField(choices=[('Y', 'SIM'), ('N', 'NÃO')], db_column='cb_has_cultivo', default='N', max_length=1)),
                ('cultivo_type', models.CharField(blank=True, db_column='ch_cultivo_type', null=True)),
                ('cultivo_area', models.CharField(blank=True, db_column='ch_cultivo_area', null=True)),
                ('month', models.CharField(choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março'), ('ABR', 'Abril'), ('MAI', 'Abril'), ('JUN', 'Junho'), ('JUL', 'JULHO'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DEZ', 'Dezembro')], db_column='cb_month', default='JAN', max_length=3)),
            ],
        ),
    ]
