# Generated by Django 4.2.6 on 2023-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='car_quantity',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='cultivo_area',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='cultivo_type',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='has_cultivo',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='type_animal',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='fetilizante_kg',
            field=models.IntegerField(blank=True, db_column='nb_fetilizante_kg', default=0, null=True),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='year',
            field=models.IntegerField(blank=True, db_column='nb_year', null=True),
        ),
    ]
