# Generated by Django 4.2.6 on 2023-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userbalance_car_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='quantity_animal',
            field=models.IntegerField(blank=True, db_column='nb_quantity_animal', default=0, null=True),
        ),
    ]
