# Generated by Django 4.2.6 on 2023-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userbalance_quantity_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='energy_per_month',
            field=models.IntegerField(blank=True, db_column='dc_energy_per_month', null=True),
        ),
    ]
