# Generated by Django 4.2.6 on 2023-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userbalance_energy_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='composted_material_quantity',
            field=models.IntegerField(blank=True, db_column='dc_composted_material_quantity', default=0, null=True),
        ),
    ]
